### ISSUE TITLE
quoteAggregator.fold

### ISSUE THREAD

**Issue by nh-chitose** [nh-chitose/r2-re#7]
空のオブジェクトが返ってくる

**Comment by mtripg6666tdr** [comment]
オブジェクト？

**Comment by mtripg6666tdr** [comment]
配列じゃなくて？

**Comment by mtripg6666tdr** [comment]
![image](https://user-images.githubusercontent.com/56076195/233932351-49dbf23e-a5b0-456b-bddb-1d4894f53554.png)
あとfold一回も参照されてないみたいだけど

**Comment by nh-chitose** [comment]
配列やね

**Comment by nh-chitose** [comment]
foldを通ると空になっちゃうからコメントアウトでfoldを通さない形にしてたけど、
渡す元データの形を変えたから結果が変わるかも

**Comment by mtripg6666tdr** [comment]
あーね

**Comment by nh-chitose** [comment]
fold NaN
システムメモリ NaN
Expected Profit NaN
NaN問題が出てきた
